# Generated by Django 4.1 on 2023-02-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
