# Generated by Django 4.1 on 2023-02-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_category_updateddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updatedDate',
        ),
    ]
