# Generated by Django 4.1 on 2023-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_review_updateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
